// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "06939f92-931e-472e-8e44-a2dc3c85e4c4");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575093609);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575093733);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575295147);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575093369);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575093249);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575093489);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575093992);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575093870);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 747520);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575093100);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0a5c301a-d077-4c49-94bc-0f29d31dc843}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575273600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575294744440");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575296552440");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575294745706");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575298345706");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215001400");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575295119");
user_pref("browser.slowStartup.averageTime", 5996);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575094727444");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Fri, 29 Nov 2019 22:22:46 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575093658);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001400");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"1ea55b9f-4748-4012-a58e-96e0a30c408b\",\"screenshots@mozilla.org\":\"7b8082e3-2d02-4e55-b6e5-5d6a05010f1c\",\"webcompat-reporter@mozilla.org\":\"353bef25-5196-41c1-b26f-38488b6c2f26\",\"webcompat@mozilla.org\":\"b296e680-5eb4-4a3f-8abb-c8154c9c9172\"}");
user_pref("idle.lastDailyNotification", 1575095250);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575093299);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575093231);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575095250);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c748057a-5bde-442f-bf21-29f92188a310");
user_pref("security.sandbox.plugin.tempDirSuffix", "a2d9b954-bce2-40b8-a57f-70994217362c");
user_pref("services.blocklist.addons.checked", 1575093562);
user_pref("services.blocklist.gfx.checked", 1575093562);
user_pref("services.blocklist.onecrl.checked", 1575093562);
user_pref("services.blocklist.pinning.checked", 1575093562);
user_pref("services.blocklist.plugins.checked", 1575093562);
user_pref("services.settings.clock_skew_seconds", -30);
user_pref("services.settings.last_update_seconds", 1575093562);
user_pref("services.settings.main.language-dictionaries.last_check", 1575093562);
user_pref("services.settings.main.sites-classification.last_check", 1575093562);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1575095250);
user_pref("toolkit.startup.last_success", 1575295116);
user_pref("toolkit.telemetry.cachedClientID", "6d848119-f9df-42ce-86e9-5db823aac8b8");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
